---

## Add Host to Inventory
- hosts: localhost
  become: no
  roles:
  - role: ec2_add_host
    tags: always

## Setup RHEL7
- hosts: RHEL7
  roles:

  ## Update packages
  - role: yum_update
    tags: yum_update
  
  ## Install / Remove Packages
  - role: yum_package
    tags: yum_package
  
  ## Enable / Disable Services
  - role: service
    tags: service
  
  ## Enable / Disable SELinux
  - role: selinux
    tags: selinux
  
  ## OS Reboot Handler for common (Handler only)
  - role: reboot
    tags: reboot

