---
## Add Host to Inventory
- hosts: localhost
  become: no
  roles:
  - role: ec2_add_host
    tags: always

## Setup ZBX
- hosts: RHEL7
  roles:

  ## Install ZBX Agent, and Setup
  - role: zabbix_agent
    tags: zabbix_agent
  
  ## Register ZBX Server
  - role: zabbix_register
    tags: zabbix_register

